### ISSUE TITLE
Handoff processes when node shutdowns gracefully

### ISSUE THREAD

**Issue by almightycouch** [bitwalker/swarm#11]
Is there a way to gracefully leave the cluster and force handoffs (passing state along) before the node goes down? If I understand correctly, currently handoffs only occur when a new node joins the cluster and not the other way around.

**Comment by bitwalker** [comment]
I hadn't considered that case, but I could certainly make it part of the implementation, either as an API call, or as part of the terminate callback in the tracker. Could you expand on the use case a bit more? It'll help me when testing.

**Comment by stavro** [comment]
@bitwalker I believe I read that you aren't using hot code upgrades for your primary use case with Swarm.  Do you preserve state across rolling upgrades?  If you're rolling out new code, existing servers will be replaced by new ones.  Do you discard the state associated with currently running processes during deployment, or do you perform a handoff before shutting down old servers?

**Comment by bitwalker** [comment]
Some percentage of processes will preserve their state during our rolling upgrades, because when a new node comes up, the cluster topology changes and handoffs occur, however we are not doing anything special to preserve state, and in fact don't rely on that. However, as mentioned above, I think adding an explicit disconnection operation which allows you to logically part from the cluster but still be able to handoff process state makes sense, and is probably what I would use instead.

**Comment by tompave** [comment]
I'm interested in this use case too.

We're evaluating moving some workloads to an Elixir+Swarm cluster where processing is distributed across the nodes automatically.
More specifically, we want to run this in Docker and on AWS ECS (it could be Kubernetes, it doesn't really change much). That means that the topology will be quite in flux, because:

* An autoscaler will start more containers when necessary (e.g. CPU usage, other custom metrics). These new containers will join the Swarm cluster once started.
* The same autoscaler will terminate some containers if the load has decreased. These will leave the cluster.
* As more lower-level hosts are added or removed (e.g. the EC2 instances where the docker containers are scheduled), the cluster topology will change and the orchestrator/scheduler will usually shift things around according to its scheduling strategy (e.g. optimize for bin packing, optimize for redundancy). This usually means that some containers will be replaced by others, running somewhere else within the same ECS cluster. When this happens, the Elixir nodes need to register and deregister.
* Deploys mean scheduling a new version of a container for a specific service, and the scheduler takes care of gradually phasing out the old version with the new one. When this happens, ideally the Elixir nodes should deregister and register with the Swarm cluster.

So, an API to signal that a node is about to leave the cluster would be great.

Alternatively, will Swarm restart a process in the current cluster nodes if the original node running the process disappears?

**Comment by bitwalker** [comment]
Swarm will restart processes if the node which owns the process disappears, but only when registered with `register_name/4`, just using the registry normally with `register_name/2` (i.e. `{:via, :swarm, name}`) does not have that behaviour.

**Comment by tompave** [comment]
Thanks @bitwalker.
Follow up question: can you please clarify what you meant here, in the [the readme](https://github.com/bitwalker/swarm#registrationprocess-grouping):

> Swarm is intended to be used by registering processes before they are created, and letting Swarm start them for you on the proper node in the cluster. This is done via `Swarm.register_name/5`. You may also register processes the normal way, i.e. `GenServer.start_link({:via, :swarm, name}, ...)`. Swarm will manage these registrations, and replicate them across the cluster, however these processes will not be moved in response to cluster topology changes.

What do you meany by "and replicate them across the cluster"?

**Comment by kelostrada** [comment]
> What do you meany by "and replicate them across the cluster"?

Other nodes will node they exist and will be able to call them, but they won't be able to restart them if the node which started them dies.

**Comment by tompave** [comment]
Oh, I see. It would replicate the info in the distributed registry. Thanks.

**Comment by roivinir** [comment]
We're having the same issue. A handover during a graceful shutdown would be super helpful !

**Comment by bschaeffer** [comment]
I think this is related to #35

**Comment by arjan** [comment]
This issue has been addressed now that #83 has been merged.
