### ISSUE TITLE
recovered process doesn't get added to group

### ISSUE THREAD

**Issue by dtrce** [bitwalker/swarm#26]
I have a test environment setup where I have two nodes talking to each other using swarm. I start 2 processes, one on each node with swarm in group :foo. When I kill node 2, node1 detects it and creates the pid locally but it does not add the process to swarm group :foo.

I am not sure if this is a bug or it is expected. If this is by design, how can I store this metadata so when it re-initialized, I can add it to the right group.

**Comment by bitwalker** [comment]
It should be added to the group automatically, this happens as part of the synchronization of metadata across nodes. If the pid is not part of the group, it's likely this synchronization did not occur for some reason. I'll take a look and see if I can reproduce. If you already have a repo I can clone which reproduces this issue, that would be helpful.

**Comment by bitwalker** [comment]
@xinz Do you have a repo I can use to reproduce?

**Comment by xinz** [comment]
@bitwalker , yes, the repo to reproduce this issue is ready now, please clone the `master` branch of https://github.com/xinz/swarm_test , the steps are:

1, `$ mix deps.get`
This issue happened in Swarm 3.0.5 and the latest bitwalker/swarm master branch;
2, `$ iex --sname app1 -S mix `
3, `$ iex --sname app2 -S mix`
4, Start a worker in app1 node with ```SwarmTest.Example.start_worker("a1")```, the a1 worker may start on app2 node, and we can find the `:foo` group membership is working via ```SwarmTest.Example.get_foos```
5, Directly exit the iex shell of app2 node, we will find the "a1" worker re-started on app1 node, but the group membership is lost now.

The above steps can reproduce this issue, and processing handoff cases we can catch this issue as well.

I have prepared a fix for this issue, in the mix.exs file of `swarm_test`, use ```{:swarm, github: "xinz/swarm"}``` to replace  ```{:swarm, "~> 3.0"}```, after update the local deps, re-run the above steps can verify this issue, please review and advise.

This commit covers:
1, nodes down case
2, :restart handoff case
3, :resume handoff case

Please let me know if this commit can submit as a PR, and then I will do that.

https://github.com/xinz/swarm/commit/247be8ccd5926aee549ab4aaa5369a4a95b500bc

**Comment by xinz** [comment]
@bitwalker  Do we have any updates? Could you please advice about https://github.com/xinz/swarm/commit/247be8ccd5926aee549ab4aaa5369a4a95b500bc when you're free?

**Comment by bitwalker** [comment]
Sorry for the delay, I'll try to look at this today or tomorrow.

**Comment by xinz** [comment]
@bitwalker it doesn't matter :)

**Comment by msw10100** [comment]
This still does not appear to be fixed in the current swarm code.  workers get lost from the group when they change nodes.  With Dina/swarm patch, workers never get misplaced.  Can you tell us if xinz's fix can be pulled into the main swarm repo?

Thanks

**Comment by bitwalker** [comment]
@msw10100 I took some time and looked at the patch and I think I can get that merged soon - I need some time to run some scenarios, but at first blush I think it's good to go.

**Comment by xinz** [comment]
Thanks for your suggestion, the PR is submitted, please review.

**Comment by narrowtux** [comment]
I encountered a similar problem and I'm unsure if it can be fixed:

When a tracked and supervised process dies, it will be restarted by the supervisor, but then it won't be re-registered by the tracker, i.e. `Swarm.registered()` is `[]`.

**Comment by narrowtux** [comment]
Oh nevermind, I found #6 later

**Comment by hubertlepicki** [comment]
I think this one can be closed then? @slashdotdash @bitwalker ?

**Comment by slashdotdash** [comment]
Fixed by #37.
