### ISSUE TITLE
process replication doesn't work if one of the nodes is started late

### ISSUE THREAD

**Issue by dtrce** [bitwalker/swarm#27]
I have 2 nodes in my swarm cluster. Here is my sys.config

`
[{kernel,
  [
    {sync_nodes_optional, ['n1@127.0.0.1', 'n2@127.0.0.1']},
    {sync_nodes_timeout, 10000}
  ]}
].
`

process replication/acknowledgment does not work right if I start node1 first, wait 20 seconds (let the timeout expire for sync_nodes) and then start node2. At this point node 1 will start with "[info] [swarm on n1@127.0.0.1] [tracker:cluster_wait] no connected nodes, proceeding without sync" and when node2 starts up, it does detect it and output following message:

iex(n1@127.0.0.1)2> [warn] [swarm on n1@127.0.0.1] [tracker:nodeup] nodeup for n2@127.0.0.1 was ignored because swarm failed to start: {:error, {:swarm, {'no such file or directory', 'swarm.app'}}}
[debug] [swarm on n1@127.0.0.1] [tracker:handle_cast] received sync request from n2@127.0.0.1
[info] [swarm on n1@127.0.0.1] [tracker:awaiting_sync_ack] received sync acknowledgement from n2@127.0.0.1
[info] [swarm on n1@127.0.0.1] [tracker:resolve_pending_sync_requests] pending sync requests cleared

But when I start a worker from node1, there is no replication of that process acknowledged by node2 but it works just fine if I start a worker from node2. 

I'm sure this is a common use case where one of the nodes dies and joins the cluster late after all the other clusters have been initialized. I am not sure what that warning is and if that has something to do with this not working as expected.

**Comment by bitwalker** [comment]
Interesting, I haven't yet encountered this in my testing or in production, I'll see if I can reproduce locally.

**Comment by bitwalker** [comment]
I think the problem is the use of the kernel settings here - Swarm can't start until the nodes are connected, but it waits the full timeout period before starting other applications. Meanwhile, node1 gets the nodeup for node2 right away, and attempts to verify that Swarm is running on node2, but because node2 is still waiting for the timeout to sync nodes to expire, the call from node1 to node2 times out/fails.

You may find that using [libcluster](https://github.com/bitwalker/libcluster), with the Epmd strategy is more flexible - it doesn't block the startup of applications on the node, but will attempt to connect to all the listed nodes at startup. So in your scenario, node1 would startup, try to connect to node2, fail because it's not up yet, then node2 would startup and attempt to connect to node1, succeed, and then both node1 and node2 would be connected to each other. To be honest, I would recommend this approach over the use of the kernel settings, because the point of the kernel settings is to ensure that the startup of both node1 and node2 is synchronized - which is rarely what you want - generally what you want is for the cluster to consist of the defined nodes, but for membership to be dynamic.

Nevertheless, I'll be looking into how to support the use of those kernel settings, but unfortunately the options are quite limited due to the nature of their behaviour.

**Comment by dtrce** [comment]
From quick skim through the libcluster repo, it seems it doesn't support advanced features such as process grouping. Is there a way to integrate swarm and lib cluster?

**Comment by bitwalker** [comment]
@dtrce libcluster is only for clustering nodes, process grouping is provided by Swarm, or by other such libraries (pg2, global, etc.)

**Comment by dtrce** [comment]
thanks! It works perfect with libcluster

**Comment by rosacris** [comment]
I was able to reproduce a similar issue without kernel settings as described in https://github.com/bitwalker/swarm/issues/44 , if I start the nodes and manually join them after seeing the without sync message, it will wait the full anti_entropy_interval before it exchanges tracker data.
