### ISSUE TITLE
Unregistering processes

### ISSUE THREAD

**Issue by uberbrodt** [bitwalker/swarm#34]
I'm not certain this is a bug, but looking for some clarification (I'm a bit new to Elixir, so sorry if this is obvious).

I integrated Swarm into an existing library using `:via` tuples. That seems to work fine, but tests that were killing a process and restarting it were failing. It seems there's a longer delay between a process being killed and `Swarm.Tracker` unregistering the process than with the Registry module.

Now that makes sense since in a distributed system it would take longer, but I'm testing on a single node so I didn't expect this to be an issue. I'm able to make the issue go away in tests by either using Process.sleep() or explicitly calling `Swarm.unregister_name`. I have an [example project](https://github.com/uberbrodt/test_swarm) that reproduces the issue. Here's the relevant code: 
```elixir
  def test() do
    uuid = "b78932b0-1265-4317-bd92-3a1a3c64789e"
    TestSwarm.Supervisor.start_worker(uuid)
    TestSwarm.Worker.worker_state(uuid)
    shutdown(uuid)
    TestSwarm.Supervisor.start_worker(uuid)
    TestSwarm.Worker.worker_state(uuid)
  end
```
And the output:
```
iex(2)> TestSwarm.Helper.test()

15:03:40.975 [debug] Starting worker for uuid: "b78932b0-1265-4317-bd92-3a1a3c64789e"

15:03:40.982 [debug] [swarm on nonode@nohost] [tracker:handle_call] registering #PID<0.178.0> as "b78932b0-1265-4317-bd92-3a1a3c64789e", with metadata %{}

15:03:40.984 [debug] [swarm on nonode@nohost] [tracker:handle_call] add_meta {:workergroup, true} to #PID<0.178.0>

15:03:40.984 [debug] Starting worker for uuid: "b78932b0-1265-4317-bd92-3a1a3c64789e"

15:03:40.984 [debug] [swarm on nonode@nohost] [tracker:handle_monitor] "b78932b0-1265-4317-bd92-3a1a3c64789e" is down: :shutdown
** (exit) exited in: GenServer.call({:via, :swarm, "b78932b0-1265-4317-bd92-3a1a3c64789e"}, {:get_state}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:737: GenServer.call/3
```
If it's not a bug (which is probably likely), is there something my Supervisor or Worker needs to be doing?
 Call `Swarm.unregister_name` from the Supervisor or in the `terminate/2` of the worker?  I also thought that maybe I need to block until the tracker is updated, but I don't see a good spot to do that.

**Comment by bitwalker** [comment]
Where are you logging the `Starting worker` bit? From `start_worker`, the worker's `start_link` or `init`? Are you starting the child asynchronously in the `start_worker` implementation (i.e. in a Task or spawned process?)

It looks to me like the worker is started asynchronously, because the worker could not be fully started until it's registration is complete (in fact, `init/1` is not even called until the registration has completed, as that's one of the first things `GenServer` does under the covers), and *if* it was complete, then `:noproc` is not possible (well, unless a bug is in play). However, reading registrations (what happens when you call `whereis_name` or do a lookup with `{:via, :swarm, name}`) is done by reading the registrations table (an ETS table) concurrently with modifications being made through the Tracker - so if you are doing the registration in parallel with the lookup, it may look like they happen in the correct order, but the read against the registry could still occur before the write does, and thus fail. Since `register_name` is blocking, calling it and then performing a subsequent lookup should always be consistent. Likewise with de-registrations. Another approach is to do something like this:

```elixir
def send_work(name, work) do
  case Swarm.whereis_name(name) do
    nil ->
      case start_worker(name) do
        {:ok, pid} -> GenServer.call(pid, work)
        {:error, {:already_registered, pid}} -> GenServer.call(pid, work)
        {:error, _} = err -> throw err
      end
    pid when is_pid(pid) -> GenServer.call(pid, work)
  end
end
```

The above provides you with some extra protection from using `:via` tuples with `call`, and also gracefully handles the inherent race when two things try to start a worker with the same name at the same time.

**Comment by uberbrodt** [comment]
Well, I don't think the worker is started asynchronously. This is how the worker is started in my example project: 
```
  def start_worker(uuid) do
    Logger.debug(fn -> "Starting worker for uuid: #{inspect uuid}" end)
    case Supervisor.start_child(__MODULE__, [uuid]) do
      {:ok, _pid} -> {:ok, uuid}
      {:error, {:already_started, _pid}} -> {:ok, uuid}
      other -> {:error, other}
    end
  end
```
Which seems close to what you're suggesting. I'm basically just leaning on the builtin GenServer functionality to let me know if the process is registered or not. But even with your code, it still seems vulnerable to the process dying and Swarm not unregistering it yet. You might try looking at the example project to see how I'm killing the process: https://github.com/uberbrodt/test_swarm/blob/master/lib/test_swarm/helper.ex

**Comment by uberbrodt** [comment]
I tried your solution and it matches on `:already_registered`, but the process is  dead so it errors out

**Comment by uberbrodt** [comment]
I think this was just a timing issue in some test cases. Closing
