### ISSUE TITLE
Swarm.registered/0 returns [] but Swarm.whereis_name/1 returns the proper remote pid 

### ISSUE THREAD

**Issue by rosacris** [bitwalker/swarm#45]
Steps to reproduce this behaviour:

1. Start a node
2. Create a process X
3. Start a second node, but do not connect it to the cluster
4. Wait for "proceeding without sync" message on the second node
5. Execute Swarm.registered/0 and Swarm.whereis_name/1 on the second node.

Swarm.registered() returns []
Swarm.whereis_name(X) returns pid of process in the first node

Why is swarm able to find the process by name but it is unable to track it as registered?

**Comment by rosacris** [comment]
I have found a way of reproducing the issue when using libcluster with Epmd
1. Start two nodes (libcluster must connected the two nodes)
2. Create a process X in node 1
3. Disconnect the nodes using Node.disconnect/1. At this point you have two process X due to the partition
4. Reconnect the nodes using Node.connect/1
5. Execute Swarm.registered/0 and Swarm.whereis_name/1 on node 2

Swarm.registered() returns [{X, pid}] on node 1
Swarm.registered() returns [] on node 2
Swarm.whereis_name(X) returns the pid of the process in both nodes

**Comment by slashdotdash** [comment]
@rosacris The call to `Swarm.whereis_name/1` [delegates to the node hosting the process](https://github.com/bitwalker/swarm/blob/master/lib/swarm/tracker/tracker.ex#L965). Therefore it will work even when the local registry is outdated. The node hosting a process can be deterministically located due to the consistent hashing of the process' name.
